# Configuration pour la production (Railway)
# Les valeurs sont récupérées automatiquement depuis les variables d'environnement de Railway

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuration du serveur
server.port=${PORT:8080}
